-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Customers"
(
    "Id" integer NOT NULL,
    "Fname" character varying COLLATE pg_catalog."default",
    "Lname" character varying COLLATE pg_catalog."default",
    "Phone" numeric,
    address character varying COLLATE pg_catalog."default",
    product_id integer,
    CONSTRAINT "Customers_pkey" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    user_id integer NOT NULL,
    "Fname" character varying COLLATE pg_catalog."default",
    "Lname" character varying COLLATE pg_catalog."default",
    "Phone" numeric,
    "Email" character varying COLLATE pg_catalog."default",
    address character varying COLLATE pg_catalog."default",
    "Product_type" character varying COLLATE pg_catalog."default",
    product_id integer,
    customers_id integer,
    CONSTRAINT "Users_pkey" PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.administrators
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Fname" text COLLATE pg_catalog."default",
    "Lname" text COLLATE pg_catalog."default",
    "Phone" numeric,
    "Email" character varying COLLATE pg_catalog."default",
    address character varying COLLATE pg_catalog."default",
    product_id integer,
    customers_id integer,
    "User_id" integer,
    delivery_id integer,
    CONSTRAINT administrators_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.deliveries
(
    "Delivery_id" integer NOT NULL,
    "Name" character varying COLLATE pg_catalog."default",
    "Phone" numeric,
    product_id integer,
    customers_id integer,
    "Date/time" date,
    "User_id" integer,
    CONSTRAINT deliveries_pkey PRIMARY KEY ("Delivery_id")
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id integer NOT NULL,
    prod_name character varying COLLATE pg_catalog."default",
    type character varying COLLATE pg_catalog."default",
    "Quantity" numeric,
    CONSTRAINT products_pkey PRIMARY KEY (product_id)
);
END;